### ISSUE TITLE
pd.read_csv warnings

### ISSUE THREAD

**Issue by MarekGierlinski** [ntanmayee/DecoDen#4]
When running `run_decoden` I receive mixed types warnings:

```
/cluster/gjb_lab/mgierlinski/projects/decoden_test/decoden/utils.py:55: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(data_folder, fname), sep="\t", names=["seqnames", "start", "end", colname])
```

Must be easy to fix.

**Comment by gvisona** [comment]
Thanks for the patience, the repository was completely reworked to be a CLI tool and I am now going through the issues. 
The warning was fixed in commit ac5e4437ac477dcb90624ae386eeecc0b33fbf61 by adding default dtypes to the read_csv call.
