### ISSUE TITLE
Missing HSR_results.ftr file

### ISSUE THREAD

**Issue by MarekGierlinski** [ntanmayee/DecoDen#8]
I ran the following commands:

```
python run_preprocess.py -i ips_bmp4_samples.csv -o newtest -bs 50 -n 5
python run_decoden.py --data_folder newtest --output_folder newtest --files_reference newtest/experiment_conditions.json --blacklist_file hg38-blacklist.chr.v2.bed --conditions "IPS_BMP4_input" "IPS_BMP4"
```

The `ips_bmp4_samples.csv` is as follows:

```
filepath,exp_name,is_control
bamchr/IPS_BMP4_input_1.bam,IPS_BMP4_input,1
bamchr/IPS_BMP4_input_2.bam,IPS_BMP4_input,1
bamchr/IPS_BMP4_1.bam,IPS_BMP4,0
bamchr/IPS_BMP4_2.bam,IPS_BMP4,0
bamchr/IPS_BMP4_3.bam,IPS_BMP4,0
```

The scripts run with no errors, until completion. However, the main results file, `HSR_results.ftr` is missing. Here are all the files created by the scripts:

```
newtest/
├── config.json
├── data
│   ├── IPS_BMP4_1_filterdup_pileup_tiled.bed
│   ├── IPS_BMP4_2_filterdup_pileup_tiled.bed
│   ├── IPS_BMP4_3_filterdup_pileup_tiled.bed
│   ├── IPS_BMP4_input_1_filterdup_pileup_tiled.bed
│   └── IPS_BMP4_input_2_filterdup_pileup_tiled.bed
├── experiment_conditions.json
└── NMF
    ├── mixing_matrix.csv
    ├── mixing_matrix.pdf
    ├── signal_matrix.ftr
    └── signal_matrix_sample.pdf
```

There is only a `signal_matrix.ftr` file, containing values `IPS_BMP4` and `IPS_BMP4_input` binned in 50-bp bins. But I cannot find NMR and HSR results.

The JSON file `experiment_conditions.json` looks fine:

```
{
 "data/IPS_BMP4_input_1_filterdup_pileup_tiled.bed": "IPS_BMP4_input",
 "data/IPS_BMP4_input_2_filterdup_pileup_tiled.bed": "IPS_BMP4_input",
 "data/IPS_BMP4_1_filterdup_pileup_tiled.bed": "IPS_BMP4",
 "data/IPS_BMP4_2_filterdup_pileup_tiled.bed": "IPS_BMP4",
 "data/IPS_BMP4_3_filterdup_pileup_tiled.bed": "IPS_BMP4"
}
```
The BED files also look correct, at least at the first glance. And yet, no result file is present.

**Comment by ntanmayee** [comment]
Very good catch!! The good news is that I fixed this in the previous commit. 

The long version is - In the rush of running decoden to produce figures for the paper, I had commented the line that writes the HSR results to disk. I didn't realise I had pushed it to `main`. 

It's fixed now.
